Repository CitrusGender/tgstation, pull requests merged in 2020-06, with the labels that each got.

#41 The Big Bad Casino Brushup
  _maps/map_files/BallMap/summer_ball.dmm
Labels: mapping

#40 Stronger Tables
  code/game/objects/structures/tables_racks.dm
  icons/mob/32x64.dmi
Labels: tweak

#31 Mafia code
  code/modules/mafia/_defines.dm
  code/modules/mafia/controller.dm
  code/modules/mafia/map_pieces.dm
  code/modules/mafia/roles.dm
  icons/obj/mafia.dmi
  tgstation.dme
  tgui/packages/tgui/components/TimeDisplay.js
  tgui/packages/tgui/components/index.js
  tgui/packages/tgui/interfaces/MafiaPanel.js
  tgui/packages/tgui/public/tgui.bundle.js
Labels: feature

#44 guys wouldnt it be funny if i omega griefed the ball
  _maps/map_files/BallMap/summer_ball.dmm
Labels: FUCK, mapping

#51 GUYS, I AM GOING TO GRIEF THE BALL
  _maps/map_files/BallMap/summer_ball.dmm
  code/game/objects/structures/beds_chairs/chair.dm
  code/modules/awaymissions/mission_code/Academy.dm
  icons/obj/rune.dmi
Labels: FUCK, mapping

#54 fikou has mapped bababooey
  _maps/map_files/BallMap/summer_ball.dmm
  code/game/objects/structures/ball_signs.dm
  code/modules/awaymissions/mission_code/Academy.dm
  code/modules/ruins/objects_and_mobs/necropolis_gate.dm
Labels: mapping, tweak

#53 Misc event stuff
  code/controllers/subsystem/lighting.dm
  code/game/objects/structures/tables_racks.dm
  code/game/turfs/open/floor.dm
Labels: feature, tweak

#55 Necropolis gate
  code/modules/reagents/chemistry/machinery/chem_dispenser.dm
  code/modules/ruins/objects_and_mobs/necropolis_gate.dm
Labels: feature, tweak

#57 Drama Alert Nation
  _maps/map_files/BallMap/summer_ball.dmm
  code/game/objects/structures/ball_signs.dm
  code/game/objects/structures/fence.dm
  code/game/objects/structures/fluff.dm
  code/game/objects/structures/grille.dm
  code/modules/awaymissions/mission_code/Academy.dm
  code/modules/mob/living/simple_animal/hostile/skeleton.dm
  icons/obj/fluff.dmi
Labels: mapping, tweak

#62 Auto prophunt
  code/controllers/subsystem/chat.dm
  code/game/machinery/computer/arena.dm
  code/modules/mafia/controller.dm
  code/modules/mafia/map_pieces.dm
  code/modules/prophunt/prophunt.dm
  tgstation.dme
  tgui/packages/tgui/interfaces/MafiaPanel.js
Labels: feature

#63 I'm Untouchable
  _maps/map_files/BallMap/summer_ball.dmm
  code/game/turfs/closed/_closed.dm
  code/game/turfs/closed/wall/mineral_walls.dm
  code/modules/clothing/head/helmet.dm
  html/changelog.html
  html/changelogs/.all_changelog.yml
  html/changelogs/AutoChangeLog-pr-51248.yml
  html/changelogs/AutoChangeLog-pr-51555.yml
  html/changelogs/AutoChangeLog-pr-51586.yml
  html/changelogs/AutoChangeLog-pr-51597.yml
  html/changelogs/AutoChangeLog-pr-51600.yml
  html/changelogs/AutoChangeLog-pr-51603.yml
  icons/mob/clothing/head.dmi
  icons/obj/clothing/hats.dmi
  icons/obj/economy.dmi
  icons/obj/smooth_structures/shuttle_window.dmi
  icons/obj/smooth_structures/tinted_window.dmi
  icons/obj/smooth_structures/window.dmi
Labels: feature, mapping, tweak

#64 Wild Ride Code
  _maps/map_files/BallMap/summer_ball.dmm
  code/game/area/areas/away_content.dm
  code/game/machinery/doors/airlock_types.dm
  code/game/turfs/closed/_closed.dm
  code/modules/projectiles/ammunition/energy/laser.dm
  code/modules/projectiles/guns/energy/laser.dm
  icons/mob/inhands/weapons/guns_lefthand.dmi
  icons/mob/inhands/weapons/guns_righthand.dmi
  icons/obj/doors/airlocks/glass_large/wood_large.dmi
  icons/obj/guns/energy.dmi
  icons/obj/machines/cloning.dmi
  icons/turf/areas.dmi
  sound/misc/EvilLaugh.ogg
  sound/misc/SpookedYa.ogg
Labels: feature, mapping

#66 Fixes replacing sand
  code/game/turfs/open/floor/plating.dm
  code/game/turfs/open/floor/plating/misc_plating.dm
Labels: tweak

#68 Minor Changes
  _maps/map_files/BallMap/summer_ball.dmm
  code/game/area/areas/away_content.dm
  code/game/machinery/buttons.dm
  code/game/objects/items/scrolls.dm
  code/modules/mob/living/simple_animal/hostile/skeleton.dm
  code/modules/research/designs/biogenerator_designs.dm
  code/modules/vending/nutrimax.dm
Labels: feature, mapping

#69 mr bones voice box
  code/game/objects/effects/temporary_visuals/miscellaneous.dm
  code/game/objects/items/mr_bones.dm
  icons/effects/effects.dmi
  sound/voice/mrbones/error_incorrect.ogg
  sound/voice/mrbones/no.ogg
  sound/voice/mrbones/repeat.ogg
  sound/voice/mrbones/roleplay.ogg
  sound/voice/mrbones/solve_the_riddle.ogg
  sound/voice/mrbones/your_problem_buddy.ogg
  tgstation.dme
Labels: DO NOT MERGE, FUCK, Stale, bug, duplicate, feature, help wanted, invalid, mapping, merge conflicts, tweak, wontfix

#72 Teleportation Landmarks
  _maps/map_files/BallMap/summer_ball.dmm
  code/game/area/Space_Station_13_areas.dm
  code/game/objects/items/scrolls.dm
  code/modules/awaymissions/mission_code/Cabin.dm
Labels: mapping, tweak

#77 Lots of Minor Changes
  _maps/map_files/BallMap/summer_ball.dmm
  code/game/objects/items/devices/radio/headset.dm
  code/game/objects/items/mr_bones.dm
  code/modules/clothing/glasses/_glasses.dm
  icons/mob/clothing/ears.dmi
  icons/mob/clothing/eyes.dmi
  icons/mob/inhands/items_lefthand.dmi
  icons/mob/inhands/items_righthand.dmi
  icons/obj/clothing/glasses.dmi
  icons/obj/stationobjs.dmi
  icons/obj/storage.dmi
Labels: feature, mapping

#80 Fixes mafia (thanks anturk)
  code/modules/mafia/map_pieces.dm
Labels: feature

#82 adds eye statue sprite
  icons/obj/statue.dmi
Labels: sprites

#85 Removes unvectored tables.
  code/game/objects/items/mr_bones.dm
  icons/obj/fluff.dmi
Labels: sprites, tweak

#81 Prophunt projectors, win and lose conditions, poki mane poggers sex, and more!
  code/game/objects/items/devices/chameleonproj.dm
  code/modules/prophunt/prophunt.dm
Labels: feature

#92 Unregistered polygons have been fixed.
  _maps/map_files/BallMap/summer_ball.dmm
  icons/mob/human_parts.dmi
  icons/obj/fluff.dmi
  icons/obj/puzzle_small.dmi
  icons/obj/stationobjs.dmi
Labels: mapping, sprites

#98 Disables Unintended Length Shifting
  _maps/map_files/BallMap/summer_ball.dmm
  code/game/objects/items/scrolls.dm
Labels: mapping, tweak

#96 Solo Antag Refactor + More Solo Antags
  code/modules/mafia/_defines.dm
  code/modules/mafia/controller.dm
  code/modules/mafia/map_pieces.dm
  code/modules/mafia/roles.dm
Labels: feature

#99 Mafia now teleports you to town square when you are put on trial
  code/modules/mafia/controller.dm
  tgui/packages/tgui/interfaces/MafiaPanel.js
  tgui/packages/tgui/public/tgui.bundle.js
Labels: feature

#101 Removes Unfiltered Charon Rifts
  _maps/map_files/BallMap/summer_ball.dmm
  code/game/objects/items/mr_bones.dm
  code/modules/clothing/glasses/_glasses.dm
Labels: feature, mapping

#105 Removes Selection Island
  _maps/map_files/BallMap/summer_ball.dmm
  code/game/objects/structures/plaques/static_plaques.dm
Labels: mapping, tweak

#111 Deletes Unregistered Chromobones
  code/game/objects/structures/plaques/static_plaques.dm
  icons/mob/human_parts.dmi
  icons/obj/fluff.dmi
Labels: sprites, tweak

#112 Lamplamplamp
  _maps/map_files/BallMap/summer_ball.dmm
Labels: invalid, mapping

#97 Blackjack
  _maps/map_files/BallMap/summer_ball.dmm
  code/game/machinery/casino_games.dm
  code/game/objects/items/toys.dm
  icons/obj/chips.dmi
  sound/items/chips.ogg
  tgstation.dme
Labels: feature
